### ISSUE TITLE
Not booting yet

### ISSUE THREAD

**Issue by nanerbs25** [nanerbs25/twrp_device_hxy_A7S#1]
I know it's not booting yet but yeah needs more fixing 
Issue: Init killing itself for no reason

Btw I got banned (again @randomuser and @nanerbs25 ) from telegram so that's why, and cant create new acc(cuz telegram thinks that the new phone number is already registered for some reason) maybe discord is fine if that's fine for you

**Comment by ghost** [comment]
> I know it's not booting yet but yeah needs more fixing Issue: Init killing itself for no reason
> 
> Btw I got banned (again @randomUser and @nanerbs25 ) from telegram so that's why, and cant create new acc(cuz telegram thinks that the new phone number is already registered for some reason) maybe discord is fine if that's fine for you

i see, please mail me your discord to `chiisaineko AT protonmail DOT com`

**Comment by ghost** [comment]
in fact we need to know why init is crashing

**Comment by ghost** [comment]
i have some idea, but need you to test

**Comment by nanerbs25** [comment]
> i have some idea, but need you to test

hmm okay, later i have some time

**Comment by ghost** [comment]
already fixed in latest commit
